Add additional info to AcquireFailure exception
level12/pals pull request #36
Opened 2022-11-15 13:27 UTC by bchopson

Fixes GH-35

2022-11-15 18:21 UTC, bchopson commented on pals/core.py
> +    def acquire(self, blocking=None, acquire_timeout=None) -> bool:
Preserves existing API (return False if lock fails to acquire

2022-11-15 18:25 UTC, bchopson commented on pals/core.py
> +    def _acquire(self, blocking=None, acquire_timeout=None) -> bool:
raises AcquireFailure if lock cannot be acquired

2022-11-15 18:46 UTC, guruofgentoo requested changes
Notes left on the docker compose arrangement. I don't see anything backwards-incompatible for the acquiring update itself, but you can run something with it to verify that. Once that's confirmed and the other notes addressed, we can merge/release.

2022-11-15 18:46 UTC, guruofgentoo commented on docker-compose.yaml
>          - '127.0.0.1:54321:5432'
We should change this to support env file overrides ala https://github.com/level12/keg/blob/master/docker-compose.yaml#L20 (needs the 2.1 version above)

2022-11-15 18:46 UTC, guruofgentoo commented on .gitignore
> +docker-compose.override.yaml
Fine to keep this, I suppose. But mostly we should be using env file overrides with vars in the compose script, so we get those file updates if they change.

2023-01-06 15:53 UTC, bchopson commented
@guruofgentoo I have the test suite passing on an internal project which uses PALS, when pinned to this commit. I think this PR is good to go.

2023-01-06 19:38 UTC, merged

2023-01-06 19:40 UTC, guruofgentoo commented
@bchopson pals 0.3.3 has been released with this update.